### ISSUE TITLE
Vault: Add secrets value filter

### ISSUE THREAD

**Issue by simonkowallik** [simonkowallik/as3ninja#23]
When the `vault` filter fetches a secret, the response does contain additional data.

example:
```jinja
# Declaration Template
{ "myAPI": {{ ninja.secrets.myAPI | vault | jsonify }} }
```

```yaml
# Template Configuration
secrets:
  myAPI:
    path: /secretOne/myAPI/sharedKey
    engine: kv1
```

response:
```json
{
  "myAPI": {
    "request_id": "308c8b5c-fadc-ff32-8543-ad611fc53d72",
    "lease_id": "",
    "renewable": false,
    "lease_duration": 2764800,
    "data": {
      "secretKey": "AES 128 4d3642df883756b0d5746f32463f6005"
    },
    "wrap_info": null,
    "warnings": null,
    "auth": null
  }
}
```

which requires a filter in the `declaration template` like this to only extract `data.secretKey`:
```jinja
{ "myAPI": {{ (ninja.secrets.myAPI | vault)['data']['secretKey'] | jsonify }} }
```

## feature
implement a filter in the template configuration (example below) to extract `data.secretKey`.

```yaml
# Template Configuration
secrets:
  myAPI:
    path: /secretOne/myAPI/sharedKey
    engine: kv1
    filter: data.secretKey # <============= Filter!
```
*Note:* KV2 should have the same syntax although the actual data location would be `data.data.secretKey`
